---
name: flutter_todo_phoenix
description: "A WebView-based wrapper for a todo list powered by Phoenix LiveView."
version: 1.0.0+1
environment:
  sdk: ">=2.19.2 <3.0.0"
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # firebase_messaging: ^14.2.1
  # firebase_core: ^2.4.1
  flutter_inappwebview: ^6.0.0-beta.22
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
